-- 테이블간 조인(join) SQL

-- 문제 1.
SELECT  E.EMPLOYEE_ID       AS "사번"
        , E.FIRST_NAME      AS "이름"
        , D.DEPARTMENT_NAME AS "부서명"
        , M.FIRST_NAME      AS "매니저이름"
FROM    EMPLOYEES E, DEPARTMENTS D, EMPLOYEES M
WHERE   E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.MANAGER_ID = M.EMPLOYEE_ID
;

-- 문제 2.
SELECT  R.REGION_NAME   AS "지역이름"
        , C.COUNTRY_NAME AS "나라이름"
FROM    REGIONS R, COUNTRIES C
WHERE   R.REGION_ID = C.REGION_ID
ORDER BY R.REGION_NAME DESC, C.COUNTRY_NAME DESC
;

-- 문제 3.
SELECT  D.DEPARTMENT_ID
        , D.DEPARTMENT_NAME
        , M.FIRST_NAME
        , L.CITY
        , C.COUNTRY_NAME
        , R.REGION_NAME
FROM    DEPARTMENTS D, EMPLOYEES M
        , LOCATIONS L, COUNTRIES C, REGIONS R
WHERE   D.MANAGER_ID = M.EMPLOYEE_ID
    AND D.LOCATION_ID = L.LOCATION_ID
    AND L.COUNTRY_ID = C.COUNTRY_ID
    AND C.REGION_ID = R.REGION_ID
ORDER BY D.DEPARTMENT_ID
;

-- 문제 4.
SELECT  H.EMPLOYEE_ID   AS "사번"
        , (E.FIRST_NAME || ' ' || E.LAST_NAME)  AS "이름"
FROM    JOB_HISTORY H, JOBS J, EMPLOYEES E
WHERE   H.JOB_ID = J.JOB_ID
    AND H.EMPLOYEE_ID = E.EMPLOYEE_ID
    AND J.JOB_TITLE = 'Public Accountant'
;

-- 문제 5.
SELECT  E.EMPLOYEE_ID       AS "사번"
        , E.FIRST_NAME      AS "이름"
        , E.LAST_NAME       AS "성"
        , D.DEPARTMENT_NAME AS "부서"
FROM    EMPLOYEES E, DEPARTMENTS D, EMPLOYEES E2
WHERE   E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
    AND E.LAST_NAME = E2.LAST_NAME(+)
    AND E.EMPLOYEE_ID <> E2.EMPLOYEE_ID
ORDER BY E.LAST_NAME
;

-- 문제 6.
SELECT  E.EMPLOYEE_ID   AS "사번"
        , E.LAST_NAME   AS "성"
        , TO_CHAR(E.HIRE_DATE, 'YYYY.MM.DD')   AS "채용일"
FROM    EMPLOYEES E, EMPLOYEES M
WHERE   E.MANAGER_ID = M.EMPLOYEE_ID
    AND E.HIRE_DATE < M.HIRE_DATE
;
